[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 100
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"